/*
 * MMIX virt boot information layout
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HW_MMIX_BOOTINFO_H
#define HW_MMIX_BOOTINFO_H

#include "exec/hwaddr.h"

#define MMIX_BOOTINFO_MAGIC 0x4d4d4958424f4f54ULL /* "MMIXBOOT" */
#define MMIX_BOOTINFO_VERSION 1
#define MMIX_BOOTINFO_FLAG_KERNEL_CMDLINE (1ULL << 0)
#define MMIX_BOOTINFO_KERNEL_CMDLINE_MAX 4095
#define MMIX_BOOTINFO_KERNEL_CMDLINE_STORAGE_SIZE \
    (MMIX_BOOTINFO_KERNEL_CMDLINE_MAX + 1)

/*
 * The boot-info block is a versioned table of unsigned 64-bit fields encoded
 * in big-endian byte order, matching MMIX's natural octa layout. Before the
 * machine ABI is released, version 1 may gain fields only at the end of the
 * table. Consumers must honor the size field and may use any known prefix.
 * Base, size, count, and geometry fields for not-yet-implemented devices
 * remain zero until the corresponding device exists. IRQ fields may expose
 * reserved machine ABI numbers before their device sources are implemented.
 * RAM_SIZE is the total configured RAM. HIGH_RAM_BASE and HIGH_RAM_SIZE
 * describe the part mapped above the MMIO aperture and are both zero when no
 * high RAM exists.
 */
typedef enum MMIXBootInfoField {
    MMIX_BOOTINFO_FIELD_MAGIC,
    MMIX_BOOTINFO_FIELD_VERSION,
    MMIX_BOOTINFO_FIELD_SIZE,
    MMIX_BOOTINFO_FIELD_FLAGS,
    MMIX_BOOTINFO_FIELD_CPU_COUNT,
    MMIX_BOOTINFO_FIELD_BOOT_CPU_ID,
    MMIX_BOOTINFO_FIELD_RAM_BASE,
    MMIX_BOOTINFO_FIELD_RAM_SIZE,
    MMIX_BOOTINFO_FIELD_LOW_RAM_BASE,
    MMIX_BOOTINFO_FIELD_LOW_RAM_SIZE,
    MMIX_BOOTINFO_FIELD_POOL_LOGICAL_BASE,
    MMIX_BOOTINFO_FIELD_POOL_PHYS_BASE,
    MMIX_BOOTINFO_FIELD_POOL_SIZE,
    MMIX_BOOTINFO_FIELD_DATA_LOGICAL_BASE,
    MMIX_BOOTINFO_FIELD_DATA_PHYS_BASE,
    MMIX_BOOTINFO_FIELD_DATA_SIZE,
    MMIX_BOOTINFO_FIELD_STACK_LOGICAL_BASE,
    MMIX_BOOTINFO_FIELD_STACK_PHYS_BASE,
    MMIX_BOOTINFO_FIELD_STACK_SIZE,
    MMIX_BOOTINFO_FIELD_MMIO_BASE,
    MMIX_BOOTINFO_FIELD_UART_BASE,
    MMIX_BOOTINFO_FIELD_UART_IRQ,
    MMIX_BOOTINFO_FIELD_TIMER_BASE,
    MMIX_BOOTINFO_FIELD_TIMER_IRQ_BASE,
    MMIX_BOOTINFO_FIELD_TIMER_IRQ_COUNT,
    MMIX_BOOTINFO_FIELD_INTC_BASE,
    MMIX_BOOTINFO_FIELD_INTC_IRQ_COUNT,
    MMIX_BOOTINFO_FIELD_VIRTIO_MMIO_BASE,
    MMIX_BOOTINFO_FIELD_VIRTIO_MMIO_IRQ,
    MMIX_BOOTINFO_FIELD_VIRTIO_MMIO_COUNT,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_CONTROL_BASE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_BASE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_SIZE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_IRQ,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_WIDTH,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_HEIGHT,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_STRIDE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_FORMAT,
    MMIX_BOOTINFO_FIELD_KERNEL_CMDLINE_ADDR,
    MMIX_BOOTINFO_FIELD_KERNEL_CMDLINE_SIZE,
    MMIX_BOOTINFO_FIELD_IPI_BASE,
    MMIX_BOOTINFO_FIELD_IPI_TARGET_COUNT,
    MMIX_BOOTINFO_FIELD_IPI_REQUEST_MASK,
    MMIX_BOOTINFO_FIELD_HIGH_RAM_BASE,
    MMIX_BOOTINFO_FIELD_HIGH_RAM_SIZE,
    MMIX_BOOTINFO_FIELD_COUNT,
} MMIXBootInfoField;

#define MMIX_BOOTINFO_OCTA_SIZE 8
#define MMIX_BOOTINFO_SIZE \
    (MMIX_BOOTINFO_FIELD_COUNT * MMIX_BOOTINFO_OCTA_SIZE)

static inline hwaddr mmix_bootinfo_field_offset(MMIXBootInfoField field)
{
    return (hwaddr)field * MMIX_BOOTINFO_OCTA_SIZE;
}

#endif
