/*
 * MMIX virt boot information layout
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HW_MMIX_BOOTINFO_H
#define HW_MMIX_BOOTINFO_H

#include "exec/hwaddr.h"

#define MMIX_BOOTINFO_MAGIC 0x4d4d4958424f4f54ULL /* "MMIXBOOT" */
#define MMIX_BOOTINFO_VERSION 1

/*
 * The boot-info block is a versioned table of unsigned 64-bit fields encoded
 * in big-endian byte order, matching MMIX's natural octa layout.
 * Not-yet-implemented device fields are present in the ABI but must be
 * written as zero until the corresponding device is added to the machine.
 */
typedef enum MMIXBootInfoField {
    MMIX_BOOTINFO_FIELD_MAGIC,
    MMIX_BOOTINFO_FIELD_VERSION,
    MMIX_BOOTINFO_FIELD_SIZE,
    MMIX_BOOTINFO_FIELD_FLAGS,
    MMIX_BOOTINFO_FIELD_CPU_COUNT,
    MMIX_BOOTINFO_FIELD_BOOT_CPU_ID,
    MMIX_BOOTINFO_FIELD_RAM_BASE,
    MMIX_BOOTINFO_FIELD_RAM_SIZE,
    MMIX_BOOTINFO_FIELD_LOW_RAM_BASE,
    MMIX_BOOTINFO_FIELD_LOW_RAM_SIZE,
    MMIX_BOOTINFO_FIELD_POOL_LOGICAL_BASE,
    MMIX_BOOTINFO_FIELD_POOL_PHYS_BASE,
    MMIX_BOOTINFO_FIELD_POOL_SIZE,
    MMIX_BOOTINFO_FIELD_DATA_LOGICAL_BASE,
    MMIX_BOOTINFO_FIELD_DATA_PHYS_BASE,
    MMIX_BOOTINFO_FIELD_DATA_SIZE,
    MMIX_BOOTINFO_FIELD_STACK_LOGICAL_BASE,
    MMIX_BOOTINFO_FIELD_STACK_PHYS_BASE,
    MMIX_BOOTINFO_FIELD_STACK_SIZE,
    MMIX_BOOTINFO_FIELD_MMIO_BASE,
    MMIX_BOOTINFO_FIELD_UART_BASE,
    MMIX_BOOTINFO_FIELD_UART_IRQ,
    MMIX_BOOTINFO_FIELD_TIMER_BASE,
    MMIX_BOOTINFO_FIELD_INTC_BASE,
    MMIX_BOOTINFO_FIELD_VIRTIO_MMIO_BASE,
    MMIX_BOOTINFO_FIELD_VIRTIO_MMIO_IRQ,
    MMIX_BOOTINFO_FIELD_VIRTIO_MMIO_COUNT,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_CONTROL_BASE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_BASE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_SIZE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_WIDTH,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_HEIGHT,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_STRIDE,
    MMIX_BOOTINFO_FIELD_FRAMEBUFFER_FORMAT,
    MMIX_BOOTINFO_FIELD_COUNT,
} MMIXBootInfoField;

#define MMIX_BOOTINFO_OCTA_SIZE 8
#define MMIX_BOOTINFO_SIZE \
    (MMIX_BOOTINFO_FIELD_COUNT * MMIX_BOOTINFO_OCTA_SIZE)

static inline hwaddr mmix_bootinfo_field_offset(MMIXBootInfoField field)
{
    return (hwaddr)field * MMIX_BOOTINFO_OCTA_SIZE;
}

#endif
