/*
 * MMIX virt machine layout
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HW_MMIX_VIRT_H
#define HW_MMIX_VIRT_H

#include "exec/hwaddr.h"

typedef enum MMIXVirtMemMap {
    MMIX_VIRT_LOW_RAM,
    MMIX_VIRT_POOL,
    MMIX_VIRT_DATA,
    MMIX_VIRT_STACK,
    MMIX_VIRT_PLATFORM_RAM,
    MMIX_VIRT_BOOTINFO,
    MMIX_VIRT_FRAMEBUFFER,
    MMIX_VIRT_MMIO,
    MMIX_VIRT_UART0,
    MMIX_VIRT_INTC,
    MMIX_VIRT_MEMMAP_COUNT,
} MMIXVirtMemMap;

enum {
    MMIX_VIRT_SHARED_IRQ_FIRST = 1,
    MMIX_VIRT_SHARED_IRQ_LAST = 15,
    MMIX_VIRT_UART0_IRQ = 1,
    MMIX_VIRT_VIRTIO_BLOCK0_IRQ = 2,
    MMIX_VIRT_FRAMEBUFFER_IRQ = 3,
    MMIX_VIRT_TIMER_IRQ_BASE = 16,
    MMIX_VIRT_INTC_CONTEXT_COUNT = 16,
    MMIX_VIRT_INTC_IRQ_COUNT =
        MMIX_VIRT_TIMER_IRQ_BASE + MMIX_VIRT_INTC_CONTEXT_COUNT,
};

enum {
    MMIX_VIRT_INTC_PENDING = 0x0000,
    MMIX_VIRT_INTC_CONTEXT_BASE = 0x1000,
    MMIX_VIRT_INTC_CONTEXT_STRIDE = 0x100,
    MMIX_VIRT_INTC_CONTEXT_ENABLE = 0x00,
    MMIX_VIRT_INTC_CONTEXT_CLAIM = 0x04,
    MMIX_VIRT_INTC_CONTEXT_COMPLETE = 0x08,
    MMIX_VIRT_INTC_SIZE =
        MMIX_VIRT_INTC_CONTEXT_BASE +
        MMIX_VIRT_INTC_CONTEXT_COUNT * MMIX_VIRT_INTC_CONTEXT_STRIDE,
};

extern const MemMapEntry mmix_virt_memmap[MMIX_VIRT_MEMMAP_COUNT];

#endif
