/*
 * MMIX virt machine layout
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HW_MMIX_VIRT_H
#define HW_MMIX_VIRT_H

enum {
    MMIX_VIRT_MAX_CPUS = 64,
    MMIX_VIRT_UART0_IRQ = 1,
    MMIX_VIRT_UART0_BAUD_BASE = 115200,
    MMIX_VIRT_UART0_REGISTER_SHIFT = 0,
    MMIX_VIRT_UART0_REGISTER_SIZE = 0x8,
    MMIX_VIRT_UART0_RESERVATION_SIZE = 0x10000,
    MMIX_VIRT_TIMER_IRQ_BASE = 16,
    MMIX_VIRT_VIRTIO_MMIO_IRQ_BASE = 2048,
    MMIX_VIRT_VIRTIO_MMIO_COUNT = 32,
    MMIX_VIRT_IPI_CONTEXT_COUNT = MMIX_VIRT_MAX_CPUS,
    MMIX_VIRT_INTC_CONTEXT_COUNT = MMIX_VIRT_MAX_CPUS,
    MMIX_VIRT_INTC_IRQ_COUNT = 8192,
    MMIX_VIRT_INTC_BITMAP_WORDS = MMIX_VIRT_INTC_IRQ_COUNT / 64,
};

#define MMIX_VIRT_UART0_BASE UINT64_C(0x0001000010000000)

#define MMIX_VIRT_INITIAL_STACK_BASE      0x0000000000010000ULL
#define MMIX_VIRT_INITIAL_STACK_SLOT_SIZE 0x0000000000008000ULL
#define MMIX_VIRT_INITIAL_STACK_AREA_SIZE \
    (MMIX_VIRT_MAX_CPUS * MMIX_VIRT_INITIAL_STACK_SLOT_SIZE)

/*
 * Framebuffer control registers are big-endian octas. XRGB8888 pixels use
 * the guest-memory byte layout 00 RR GG BB, independent of host byte order.
 */
enum {
    MMIX_VIRT_FRAMEBUFFER_WIDTH = 1024,
    MMIX_VIRT_FRAMEBUFFER_HEIGHT = 768,
    MMIX_VIRT_FRAMEBUFFER_BPP = 32,
    MMIX_VIRT_FRAMEBUFFER_STRIDE = 4096,
    MMIX_VIRT_FRAMEBUFFER_FORMAT_XRGB8888 = 1,
    MMIX_VIRT_FRAMEBUFFER_REG_WIDTH = 0x00,
    MMIX_VIRT_FRAMEBUFFER_REG_HEIGHT = 0x08,
    MMIX_VIRT_FRAMEBUFFER_REG_STRIDE = 0x10,
    MMIX_VIRT_FRAMEBUFFER_REG_FORMAT = 0x18,
    MMIX_VIRT_FRAMEBUFFER_REG_BASE = 0x20,
    MMIX_VIRT_FRAMEBUFFER_REG_SIZE = 0x28,
    MMIX_VIRT_FRAMEBUFFER_REG_FLUSH = 0x30,
    MMIX_VIRT_FRAMEBUFFER_CONTROL_MMIO_SIZE = 0x1000,
};

enum {
    MMIX_VIRT_INTC_GLOBAL_SOURCE_COUNT = 0x0000,
    MMIX_VIRT_INTC_GLOBAL_CONTEXT_COUNT = 0x0008,
    MMIX_VIRT_INTC_GLOBAL_PENDING_BASE = 0x1000,
    MMIX_VIRT_INTC_GLOBAL_SIZE = 0x10000,
    MMIX_VIRT_INTC_CONTEXTS_OFFSET = 0x04000000,
    MMIX_VIRT_INTC_CONTEXT_STRIDE = 0x10000,
    MMIX_VIRT_INTC_CONTEXT_ENABLE_BASE = 0x000,
    MMIX_VIRT_INTC_CONTEXT_CLAIM = 0x800,
    MMIX_VIRT_INTC_CONTEXT_COMPLETE = 0x808,
    MMIX_VIRT_INTC_CONTEXT_REGISTER_SIZE = 0x1000,
    MMIX_VIRT_INTC_RESERVATION_SIZE = 0x08000000,
};

#define MMIX_VIRT_INTC_BASE UINT64_C(0x0001000030000000)
#define MMIX_VIRT_INTC_CONTEXT_BASE \
    (MMIX_VIRT_INTC_BASE + MMIX_VIRT_INTC_CONTEXTS_OFFSET)

enum {
    MMIX_VIRT_IPI_GLOBAL_REGISTER_SIZE = 0x1000,
    MMIX_VIRT_IPI_CONTEXTS_OFFSET = 0x10000,
    MMIX_VIRT_IPI_CONTEXT_STRIDE = 0x10000,
    MMIX_VIRT_IPI_CONTEXT_REGISTER_SIZE = 0x1000,
    MMIX_VIRT_IPI_RESERVATION_SIZE = 0x04000000,
};

#define MMIX_VIRT_IPI_BASE UINT64_C(0x0001000024000000)
#define MMIX_VIRT_IPI_CONTEXT_BASE \
    (MMIX_VIRT_IPI_BASE + MMIX_VIRT_IPI_CONTEXTS_OFFSET)

enum {
    MMIX_VIRT_TIMER_TIME = 0x0000,
    MMIX_VIRT_TIMER_CONTEXT_COUNT = MMIX_VIRT_MAX_CPUS,
    MMIX_VIRT_TIMER_GLOBAL_REGISTER_SIZE = 0x1000,
    MMIX_VIRT_TIMER_CONTEXTS_OFFSET = 0x10000,
    MMIX_VIRT_TIMER_CONTEXT_STRIDE = 0x10000,
    MMIX_VIRT_TIMER_CONTEXT_REGISTER_SIZE = 0x1000,
    MMIX_VIRT_TIMER_RESERVATION_SIZE = 0x04000000,
    MMIX_VIRT_TIMER_CONTEXT_COMPARE = 0x00,
    MMIX_VIRT_TIMER_CONTEXT_CONTROL = 0x08,
    MMIX_VIRT_TIMER_CONTEXT_STATUS = 0x10,
    MMIX_VIRT_TIMER_CONTROL_ENABLE = 0x01,
    MMIX_VIRT_TIMER_CONTROL_IRQ_ENABLE = 0x02,
    MMIX_VIRT_TIMER_STATUS_PENDING = 0x01,
};

#define MMIX_VIRT_TIMER_BASE UINT64_C(0x0001000020000000)
#define MMIX_VIRT_TIMER_CONTEXT_BASE \
    (MMIX_VIRT_TIMER_BASE + MMIX_VIRT_TIMER_CONTEXTS_OFFSET)

#endif
